apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test4
  annotations:
    github.com/project-slug: nordrichbynordcloud/test4
  description: Repository for test4 created via github-template workflow.
  tags:
    - github
spec:
  type: repository
  owner: nordrichbynordcloud
  lifecycle: experimental